---
- name: Check `paru` Installed
  become: true
  become_user: "{{ user }}"
  shell: |
    #!/bin/sh
    if which /usr/bin/paru >/dev/null; then
      echo "Installed"
    else
      echo "Not Installed"
    fi
  register: check_paru_installed
  changed_when: check_paru_installed.stdout != "Installed"

- set_fact:
    should_install_paru: '{{ check_paru_installed.stdout != "Installed" }}'

- name: Install `paru`
  block:
    - name: Update and Upgrade `pacman` Packages
      pacman:
        update_cache: true
        upgrade: true

    - name: Install Base Packages with `pacman`
      pacman:
        name:
          - git
          - make
          - sudo
          - zsh
        state: present

    - name: Ensure Directory `/opt/paru-bin` Exists
      file:
        path: /opt/paru-bin
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: true

    - name: Clone `paru` Repository
      become: true
      become_user: "{{ user }}"
      git:
        repo: https://aur.archlinux.org/paru-bin.git
        dest: /opt/paru-bin

    - name: Install `paru` Using `makepkg`
      become: true
      become_user: "{{ user }}"
      shell: |
        #!/bin/sh
        cd /opt/paru-bin
        /usr/bin/makepkg -si --noconfirm

  when: should_install_paru == true

- name: Check Updates
  become: true
  become_user: "{{ user }}"
  shell: |
    #!/bin/sh
    /usr/bin/paru -Qu | wc -l
  register: check_updates
  changed_when: check_updates.stdout != "0"

- set_fact:
    should_install_updates: check_updates.stdout != "0"

- name: Update Packages
  become: true
  become_user: "{{ user }}"
  shell: |
    #!/bin/sh
    /usr/bin/paru -Syu --noconfirm
  when: should_install_updates == true
